### PR TITLE
fix: incorrect machine selection during create

### LINKED ISSUE #74: Cross-namespace machine selection when MachineDeployments have the same name
### Description

**Observed Behavior**:
When two MachineDeployment resources with the same name exist in different namespaces, Karpenter may incorrectly select a machine belonging to the wrong MachineDeployment during the unclaimed machine polling phase.

**Expected Behavior**:
Karpenter should select unclaimed machine of the same machine deployment that it scaled.

**Reproduction Steps (intermittent)**:
1. Create two MachineDeployment resources with the same name in different namespaces. (say `worker-md0` in namespace `dev` and `dev2`)                                                                                                           
2. Scale-up in both of them up by 1, so they have atleast 1 unclaimed machine.
3. Now perform auto scale up in one of the cluster via karpenter.
4. Observe that Karpenter may associate a machine from the other namespace with the NodeClaim. (It will replicate sometime depending on what the machine listing returns as first item)
5. **IF** nodeclaim incorrectly associated, you can notice that the new machine has joined the cluster, but nodeclaim status is Unknown. The label of the nodeclaim points to machine in the different namespace). NodeClaim will stay stuck at Unknown status. Also the new machine just added due to scale up is not managed by karpenter.

**Versions**:
- Karpenter Cluster-API Provider Version: `v0.2.0`
- Cluster-API Version and Provider: Docker Infrastructure provider. (Everything at `v1.12.4`)
- Kubernetes Version (`kubectl version`): `v1.35.0`

### PR DESCRIPTION
**Pull request by parthyadav3105**
When MachineDeployments with the same name exist in multiple namespaces, Karpenter may select a machine belonging to a different MachineDeployment than expected.

This patch fixes this by scoping machine listing to the namespace of the target MachineDeployment to prevent cross-namespace machine selection.

Fixes #74

### CODE REVIEW

File: pkg/providers/machine/machine.go [hunk 1]
```diff
@@ -74,10 +74,15 @@ func (p *DefaultProvider) GetByProviderID(ctx context.Context, providerID string
 	return nil, nil
 }
 
-func (p *DefaultProvider) List(ctx context.Context, selector *metav1.LabelSelector) ([]*capiv1beta1.Machine, error) {
+func (p *DefaultProvider) List(ctx context.Context, namespaces string, selector *metav1.LabelSelector) ([]*capiv1beta1.Machine, error) {
```
Comment (elmiko) [inline pkg/providers/machine/machine.go]: could we name this variable `namespace`, unless the intention is to hold multiple namespace?

File: pkg/providers/machine/machine_test.go [hunk 2]
```diff
@@ -151,7 +151,7 @@ var _ = Describe("Machine DefaultProvider.List method", func() {
 		machine := newMachine("karpenter-1", "karpenter-cluster", true)
 		Expect(cl.Create(context.Background(), machine)).To(Succeed())
 
-		machines, err := provider.List(context.Background(), &NodePoolMemberLabelSelector)
+		machines, err := provider.List(context.Background(), testNamespace, &NodePoolMemberLabelSelector)
```
Comment (elmiko) [inline pkg/providers/machine/machine_test.go:156]: could we add another machine to this test so that we can exercise the namespace selection logic?

**Review by elmiko — COMMENTED** [review]
looking mostly good, just a couple suggestions.

**Review by elmiko — COMMENTED** [review]
looks great, thanks for the updates!

/approve

cc @maxcao13 would you take a look for lgtm

**Comment by maxcao13** [comment]
I think we need to rebase, the e2e is still cloning capk 0.10.0, not 0.10.1

**Comment by parthyadav3105** [comment]
@maxcao13, I have rebased. It seems workflows do trigger automatically. Can you please trigger it.

**Comment by maxcao13** [comment]
I see the e2e got triggered automatically, and passed. Thanks!

/lgtm

**Comment by elmiko** [comment]
> I see the e2e got triggered automatically, and passed. Thanks!

i triggered it from the web page. i think we need to enable ok-to-test on this repo.
